[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "pillow>=12.1.0",
    "qrcode>=8.2",
    "streamlit>=1.52.2",
    "types-qrcode>=8.2.0.20250914",
]
