[browser]
gatherUsageStats = false

[server]
port = 5000
address = "0.0.0.0"
headless = true
enableCORS = true
enableXsrfProtection = false
enableWebsocketCompression = false

[theme]
primaryColor = "#4CAF50"
backgroundColor = "#111111"
secondaryBackgroundColor = "#222222"
textColor = "#FFFFFF"
font = "sans serif"
